/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Thom/Union
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_PREFS_SAVE                          0
#define GD_PREFS_USE                           1
#define GD_PREFS_CANCEL                        2
#define GD_PREFS_PATCHDELETE                   3
#define GD_PREFS_PATCHOPEN                     4
#define GD_PREFS_TRASHCANS                     5
#define GD_PREFS_ADD                           6
#define GD_PREFS_REMOVE                        7
#define GD_PREFS_APPWINDOW                     8
#define GD_PREFS_APPICON                       9
#define GD_PREFS_FORCEDELETE                   10
#define GD_PREFS_FD_ADD                        11
#define GD_PREFS_FD_REMOVE                     12
#define GD_PREFS_OVERWRITE                     13
#define GD_PREFS_FREEDISK                      14
#define GD_PREFS_ASKBEFOREDELETE               15
#define GD_PREFS_APPMENU                       16
#define GD_PREFS_ANIMATIONS                    17
#define GD_PREFS_HIDECLOSESALL                 18
#define GD_PREFS_DELETEZEROK                   19
#define GD_PREFS_SOUND                         20
#define GD_PREFS_GETSOUND                      21

#define GDX_PREFS_SAVE                         0
#define GDX_PREFS_USE                          1
#define GDX_PREFS_CANCEL                       2
#define GDX_PREFS_PATCHDELETE                  3
#define GDX_PREFS_PATCHOPEN                    4
#define GDX_PREFS_TRASHCANS                    5
#define GDX_PREFS_ADD                          6
#define GDX_PREFS_REMOVE                       7
#define GDX_PREFS_APPWINDOW                    8
#define GDX_PREFS_APPICON                      9
#define GDX_PREFS_FORCEDELETE                  10
#define GDX_PREFS_FD_ADD                       11
#define GDX_PREFS_FD_REMOVE                    12
#define GDX_PREFS_OVERWRITE                    13
#define GDX_PREFS_FREEDISK                     14
#define GDX_PREFS_ASKBEFOREDELETE              15
#define GDX_PREFS_APPMENU                      16
#define GDX_PREFS_ANIMATIONS                   17
#define GDX_PREFS_HIDECLOSESALL                18
#define GDX_PREFS_DELETEZEROK                  19
#define GDX_PREFS_SOUND                        20
#define GDX_PREFS_GETSOUND                     21

#define Prefs_CNT 22

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *DummyWnd;
extern struct Window        *PrefsWnd;
extern struct Gadget        *PrefsGList;
extern struct Menu          *DummyMenus;
extern struct Gadget        *PrefsGadgets[22];
extern struct IClass        *getClass;
extern struct _Object       *getImage;
extern UWORD                 DummyLeft;
extern UWORD                 DummyTop;
extern UWORD                 DummyWidth;
extern UWORD                 DummyHeight;
extern UWORD                 PrefsLeft;
extern UWORD                 PrefsTop;
extern UWORD                 PrefsWidth;
extern UWORD                 PrefsHeight;
extern UBYTE                *DummyWdt;
extern UBYTE                *PrefsWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UBYTE                *PREFS_OVERWRITE1Labels[];
extern struct IntuiText      PrefsIText[];
extern struct NewMenu        DummyNewMenu[];
extern UWORD                 PrefsGTypes[];
extern struct NewGadget      PrefsNGad[];
extern ULONG                 PrefsGTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenDummyWindow( void );
extern void CloseDummyWindow( void );
extern void PrefsRender( void );
extern int OpenPrefsWindow( void );
extern void ClosePrefsWindow( void );
extern UWORD ComputeX( UWORD );
extern UWORD ComputeY( UWORD );
extern void ComputeFont( UWORD , UWORD );
